[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remmappins = [
    "@openzeppeling/=dependencies/dependencies/openzeppelin-contracts/contracts",
]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[dependencies]
solmate = { version = "6.7.0" }
